### ISSUE TITLE
Fix lazy constraints

### ISSUE THREAD

**Issue by solliolli** [gamma-opt/DecisionProgramming.jl#20]
This description will be about the probability cut since it's the one I've been debugging, but some of these points will also need to be addressed for the active paths cut. I created a branch _probability_cut_ with some quick fixes, but we might want to think about these some more. 

### The tolerance (epsilon) doesn't work as an absolute tolerance
- Really simple example: you participate in a lottery where you have an 80% chance to win one euro and a 20% chance to lose four. The influence diagram corresponding to this problem is a single chance node and a value node, you don't even get to decide whether or not you want to participate. Thus, there are two paths and the solution is trivial: both of them should be active. What this version of the probability cut does is set epsilon to 0.2, then check if the probability sum is between 0.8 and 1.2 (isapprox with atol=0.2). The solution where we ignore the possibility of losing is valid, and we get expected value of one euro.
- In an older implementation of the framework, the probability sum is calculated in a different way. First the active paths are defined as those whose probability is at least epsilon, then πsum is calculated as the sum of probabilities π for those active paths.
- The quick fix I did was to remove the epsilon and use the default tolerance for the isapprox function

### The flag breaks things for an unknown reason
- In general, it is a good idea to avoid adding the same constraint multiple times and the flag should thus be a good idea
- According to [the documentation](https://www.gurobi.com/documentation/9.1/refman/lazyconstraints.html), setting the Gurobi parameter LazyConstraints=1 should "avoid certain reductions and transformations that are incompatible with lazy constraints"
- In practice, it seems like the lazy constraint might be added before presolving the model, and dropped in the presolving process despite correctly setting the parameter.
- The quick fix I did was to remove the flag. 

### Possible incompatibility between forbidden paths and probability cuts?
- In a special case, the upper and lower bound might not converge. This happened when using the hard lower bound constraints, forbidden paths and lazy probability cuts at the same time. The primal bound converged to the correct solution without the probability cuts because of the hard lower bound constraints, but the dual bound was zero. The problem was solved by deactivating the hard lower bound constraints. Need to look into this more.

**Comment by solliolli** [comment]
We should also think about how useful it is to think about each of these if they are not relevant in the new formulation we're developing

**Comment by solliolli** [comment]
If this wasn't enough bugs, I was looking at the [JuMP docs](https://jump.dev/MathOptInterface.jl/stable/reference/callbacks/) and found that "At most one callback of each type can be registered. If an optimizer already has a function for a callback type, and the user registers a new function, then the old one is replaced." 

This means that if we add both lazy constraints, the first one will be replaced. The fix for this would be to have a single function for adding the lazy constraints, instead of the separate functions we have now.

**Comment by odow** [comment]
> In general, it is a good idea to avoid adding the same constraint multiple times

Depending on which solver you use, this can cause very bad things. (See the warning at the bottom of https://jump.dev/JuMP.jl/stable/manual/callbacks/#Lazy-constraints.)

> setting the Gurobi parameter LazyConstraints=1

No need to set this parameter. We do it automatically:
https://github.com/jump-dev/Gurobi.jl/blob/6484ba968b09526f13bb8cb5a1fe27abc82bb627/src/MOI_wrapper/MOI_callbacks.jl#L175-L176
There are certain presolve steps like dual reductions that are invalidated by lazy constraints.

> In practice, it seems like the lazy constraint might be added before presolving the model, and dropped in the presolving process despite correctly setting the parameter.

Do you have a minimal working example? This seems like a bad bug? I should note that during the solving process, you may visit solutions that were previously invalidated. Only the _final_ solution is guaranteed to satisfy all of the lazy constraints that were added.

> At most one callback of each type can be registered. If an optimizer already has a function for a callback type, and the user registers a new function, then the old one is replaced.

Good find! this should be made more explicit in the documentation. At the moment it's buried pretty deeply.

**Comment by solliolli** [comment]
> Do you have a minimal working example?

I created a quick example, basically a simplified version of the [used car buyer](https://gamma-opt.github.io/DecisionProgramming.jl/dev/examples/used-car-buyer/) example where I found this bug. You choose between two lotteries. In the first one, you lose 100 with a probability of 20% and win 60 with a probability of 80%. In the second one, the probabilities are the same, and the payoffs are 15 and 35 (a lower risk lottery where you can't lose money or whatever you're betting). The expected values of these lotteries are 28 and 31, respectively, so as a risk-neutral decision-maker you should choose the second one. The selection is represented by the variables y, and the variables x are the probabilities, similar to the pi-variables in the Decision Programming formulation. The lazy constraint states that the sum of probabilities must be 1, and together with the other constraints, two of the x-variables should be set to zero and the other two to their upper bounds.

```
using JuMP, Gurobi


function test_cut(model, vars)
    # Add the constraints only once
    flag = false
    function test_cut(cb_data)
        xsum = sum(callback_value(cb_data, x) for x in vars)
        println("sum is $xsum, should be 1")
        flag && return
        if !isapprox(xsum, 1.0)
            con = @build_constraint(sum(x) == 1.0)
            MOI.submit(model, MOI.LazyConstraint(cb_data), con)
            println("added constraint $con")
            flag = true
        end
    end
    MOI.set(model, MOI.LazyConstraintCallback(), test_cut)
end

model = Model()
optimizer = optimizer_with_attributes(
    () -> Gurobi.Optimizer(),
    "LazyConstraints" => 1,
    # "Presolve"        => 0,
)
set_optimizer(model, optimizer)

@variable(model, x[1:4] >= 0)
@variable(model, y[1:2], Bin)
@objective(model, Max, -100*x[1] + 60*x[2] + 15*x[3] + 35*x[4])
@constraint(model, x[1] <= 0.2)
@constraint(model, x[2] <= 0.8)
@constraint(model, x[3] <= 0.2)
@constraint(model, x[4] <= 0.8)
@constraint(model, [i=1:2], x[i] <= y[1])
@constraint(model, [i=3:4], x[i] <= y[2])
@constraint(model, sum(y) == 1)
test_cut(model, x)


println(model)
optimize!(model)

println(value.(y))
println(value.(x))
```

If the line _flag = true_ is commented out, the lazy constraint can be added multiple times and the final solution is correct. If the line is left as is, the constraint will not be active in the final solution, and the optimal solution is to pick the first lottery and ignore the possibility of losing.

I'm using Julia 1.5.1 and the package versions are JuMP 0.21.4 and Gurobi 0.9.14

**Comment by helmihankimaa** [comment]
Thanks solliolli for the example! I experimented with it and found that when the presolve is turned off, the lazy constraint was added to the model but the solution was still erroneous x = [0, 0.8, 0, 0]. This implies that the lazy constraint is deleted somewhere else than in the presolving phase.

I then ran the code with both the presolve and the flag disabled (the *flag = true* line commented out) and got the correct solution. However, I found that in this case the lazy constraint was added and deleted several times during the solution process, which surprised me. Is this the expected behaviour?

**Comment by odow** [comment]
I think this is expected behavior, not a bug. It's one of the severe difficulties of generalizing solver callbacks via JuMP. I'll clarify with Gurobi support

We should make the JuMP documentation clearer that:

> during the solving process, you may visit solutions that were previously invalidated. Only the final solution is guaranteed to satisfy all of the lazy constraints that were added.

You can't assume that it is sufficient to add the lazy constraint once. 

```Julia
julia> using JuMP, Gurobi

julia> function test_cut(model, vars)
           # Add the constraints only once
           flag = false
           function test_cut(cb_data)
               xsum = sum(callback_value(cb_data, x) for x in vars)
               @warn("sum is $xsum, should be 1")
               flag && return
               if !isapprox(xsum, 1.0)
                   con = @build_constraint(sum(x) == 1.0)
                   MOI.submit(model, MOI.LazyConstraint(cb_data), con)
                   @info("added constraint $con")
                   # flag = true
               end
           end
           MOI.set(model, MOI.LazyConstraintCallback(), test_cut)
       end
test_cut (generic function with 1 method)

julia> model = Model()
A JuMP Model
Feasibility problem with:
Variables: 0
Model mode: AUTOMATIC
CachingOptimizer state: NO_OPTIMIZER
Solver name: No optimizer attached.

julia> optimizer = optimizer_with_attributes(
           () -> Gurobi.Optimizer(),
           "LazyConstraints" => 1,
           # "Presolve"        => 0,
       )
MathOptInterface.OptimizerWithAttributes(var"#130#131"(), Pair{MathOptInterface.AbstractOptimizerAttribute, Any}[MathOptInterface.RawParameter("LazyConstraints") => 1])

julia> set_optimizer(model, optimizer)
Academic license - for non-commercial use only - expires 2021-09-05

julia> @variable(model, x[i=1:4] >= 0)
4-element Vector{VariableRef}:
 x[1]
 x[2]
 x[3]
 x[4]

julia> @variable(model, y[1:2], Bin)
2-element Vector{VariableRef}:
 y[1]
 y[2]

julia> @objective(model, Max, -100*x[1] + 60*x[2] + 15*x[3] + 35*x[4])
-100 x[1] + 60 x[2] + 15 x[3] + 35 x[4]

julia> @constraint(model, x[1] <= 0.2)
x[1] ≤ 0.2

julia> @constraint(model, x[2] <= 0.8)
x[2] ≤ 0.8

julia> @constraint(model, x[3] <= 0.2)
x[3] ≤ 0.2

julia> @constraint(model, x[4] <= 0.8)
x[4] ≤ 0.8

julia> @constraint(model, [i=1:2], x[i] <= y[1])
2-element Vector{ConstraintRef{Model, MathOptInterface.ConstraintIndex{MathOptInterface.ScalarAffineFunction{Float64}, MathOptInterface.LessThan{Float64}}, ScalarShape}}:
 x[1] - y[1] ≤ 0.0
 x[2] - y[1] ≤ 0.0

julia> @constraint(model, [i=3:4], x[i] <= y[2])
1-dimensional DenseAxisArray{ConstraintRef{Model, MathOptInterface.ConstraintIndex{MathOptInterface.ScalarAffineFunction{Float64}, MathOptInterface.LessThan{Float64}}, ScalarShape},1,...} with index sets:
    Dimension 1, 3:4
And data, a 2-element Vector{ConstraintRef{Model, MathOptInterface.ConstraintIndex{MathOptInterface.ScalarAffineFunction{Float64}, MathOptInterface.LessThan{Float64}}, ScalarShape}}:
 x[3] - y[2] ≤ 0.0
 x[4] - y[2] ≤ 0.0

julia> @constraint(model, sum(y) == 1)
y[1] + y[2] = 1.0

julia> test_cut(model, x)
(::var"#test_cut#128"{Model, Vector{VariableRef}, Bool}) (generic function with 1 method)

julia> optimize!(model)
Gurobi Optimizer version 9.1.0 build v9.1.0rc0 (mac64)
Thread count: 4 physical cores, 8 logical processors, using up to 8 threads
Optimize a model with 9 rows, 6 columns and 14 nonzeros
Model fingerprint: 0x8f5637c2
Variable types: 4 continuous, 2 integer (2 binary)
Coefficient statistics:
  Matrix range     [1e+00, 1e+00]
  Objective range  [2e+01, 1e+02]
  Bounds range     [0e+00, 0e+00]
  RHS range        [2e-01, 1e+00]
┌ Warning: sum is 0.8, should be 1
└ @ Main REPL[195]:6
[ Info: added constraint ScalarConstraint{AffExpr, MathOptInterface.EqualTo{Float64}}(x[1] + x[2] + x[3] + x[4], MathOptInterface.EqualTo{Float64}(1.0))
Presolve removed 5 rows and 1 columns
Presolve time: 0.00s
Presolved: 4 rows, 5 columns, 8 nonzeros
Variable types: 4 continuous, 1 integer (1 binary)

Root relaxation: objective 4.800000e+01, 3 iterations, 0.00 seconds
┌ Warning: sum is 0.8, should be 1
└ @ Main REPL[195]:6
[ Info: added constraint ScalarConstraint{AffExpr, MathOptInterface.EqualTo{Float64}}(x[1] + x[2] + x[3] + x[4], MathOptInterface.EqualTo{Float64}(1.0))
┌ Warning: sum is 1.0, should be 1
└ @ Main REPL[195]:6

    Nodes    |    Current Node    |     Objective Bounds      |     Work
 Expl Unexpl |  Obj  Depth IntInf | Incumbent    BestBd   Gap | It/Node Time

*    0     0               0      31.0000000   31.00000  0.00%     -    0s

Cutting planes:
  Lazy constraints: 1

Explored 0 nodes (4 simplex iterations) in 0.06 seconds
Thread count was 8 (of 8 available processors)

Solution count 1: 31 

Optimal solution found (tolerance 1.00e-04)
Best objective 3.100000000000e+01, best bound 3.100000000000e+01, gap 0.0000%

User-callback calls 45, time in user-callback 0.06 sec

julia> println(value.(y))
[0.0, 1.0]

julia> println(value.(x))
[0.0, 0.0, 0.19999999999999996, 0.8]
```

**Comment by odow** [comment]
Confirmed with Gurobi support that this is expected behavior.

**Comment by solliolli** [comment]
I'm slightly confused about the combination of

> Only the final solution is guaranteed to satisfy all of the lazy constraints that were added.

and

> You can't assume that it is sufficient to add the lazy constraint once.

To me, these feel somewhat contradictory. Basically the final solution should satisfy the first constraint that we add, but on the other hand we can't assume that. What am I understanding wrong?

**Comment by odow** [comment]
Perhaps I meant:

> Only the final solution is guaranteed to satisfy all of the lazy constraints that ***could*** added.

If you add a lazy constraint and at some future point Gurobi removes it, one of two things must happen: Gurobi calls the lazy constraint again at the same point, or the final solution satisfies the constraint without re-adding it.
